### PR TITLE
Add main menu art (display one at random), add game over artwork.

### PR DESCRIPTION
**Pull request by belovachap**
I used ChatGPT to generate some artwork and load one of the images at random on the Main Menu. I also asked ChatGPT to make some "Game Over" images we could use in the future once we have that kind of functionality. The AI image generator is kind of fun, I use Python to hit their API. I'll have to show you how that's done some day, it can be really useful sometimes.

image

### CODE REVIEW

**Comment by spicewooddev** [comment]
Looking awesome!! Sorry I couldn't work on it today, I'm not at home right now but tomorrow in the afternoon I'll work more on the depth charges.

**Comment by belovachap** [comment]
> Looking awesome!! Sorry I couldn't work on it today, I'm not at home right now but tomorrow in the afternoon I'll work more on the depth charges.

No rush, take as much time as you want to work on which ever parts seem interesting or useful :)

**Comment by spicewooddev** [comment]
Are you here at the programmer meetup today? All the rooms are full today and I'm not sure where you are

**Comment by belovachap** [comment]
> Are you here at the programmer meetup today? All the rooms are full today and I'm not sure where you are

Sorry, I won't make it today :( I missed seeing your RSVP and didn't think anyone was coming. Let me know if you want to meet up in person to talk about anything this week (my schedule is usually pretty open). If not I can make sure to come next week. Apologies again for making your show up to the library in vain :(

**Comment by spicewooddev** [comment]
it's alright. i ended up working on the SubBoom in the meantime. I tried using the BoxCollider2D but the two main ways I did ended up not working at all. Not even the debug messages I set up worked in console either, but at least it didn't throw any errors at me.

I think I just figured out why though, and it's maybe because of the differences between Collider2D and Collision2D but im honestly not sure what the differences between those two are. Since I can't send cs files on here, I'll send a zip file instead that will only have the cs file in it of what I've worked on so far. I won't send a pull request yet until we figure out why the collisions aren't working.
[SubBoom.zip](https://github.com/user-attachments/files/16577154/SubBoom.zip)

**Pull request merged**
